# Dependencies
markdown:         rdiscount
pygments:         true # false

# Permalinks
permalink:        pretty

# Server
destination:      ./_gh_pages
host:             0.0.0.0
port:             9001
baseurl:          http://fateclab.github.io/fatec-bootstrap
url:              http://localhost:9001 # jekyll serve --watch --baseurl=
encoding:         UTF-8

exclude:          ["vendor"]

# Custom vars
current_version_fatec:  3.1.1-3.1.1
current_version:  3.1.1
repo:             https://github.com/fateclab/fatec-bootstrap
sass_repo:        https://github.com/fateclab/fatec-bootstrap-sass

download:
  source:         https://github.com/fateclab/fatec-bootstrap/archive/3.1.1-3.1.1.zip
  dist:           https://github.com/fateclab/fatec-bootstrap/archive/3.1.1-3.1.1.zip
  sass:           https://github.com/fateclab/fatec-bootstrap/archive/3.1.1-3.1.1.zip

blog:             http://blog.getbootstrap.com
expo:             http://expo.getbootstrap.com

cdn:
  css:            //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/fatec-bootstrap.min.css
  css_theme:      //netdna.bootstrapcdn.com/bootstrap/3.1.1/css/bootstrap-theme.min.css
  js:             //netdna.bootstrapcdn.com/bootstrap/3.1.1/js/fatec-bootstrap.min.js
